MvcMovie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMovie.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TourView()
        {
            
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MvcMovie/Controllers/NoteListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMovie.Controllers
{
    public class NoteListController : Controller
    {
        // GET: NoteList
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Word()
        {
            return View();
        }
        public ActionResult Detail()
        {
            return View();
        }
        public ActionResult Sentences()
        {
            return View();
        }
        public ActionResult Phases()
        {
            return View();
        }
        
    }
}

MvcMovie/Controllers/TourMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMovie.Controllers
{
    public class TourMVCController : Controller
    {
        // GET: TourMVC
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index1A()
        {
            return View("Index");
        }

        public String Index1B()
        {
            return "I AM STRING";
        }
        public ActionResult Index1C()
        {
            return Redirect("http://www.yahoo.com.tw");
        }
        public ActionResult Index1D()
        {
            ViewData["A"] = "I AM VIEW DATRAA";
            ViewBag.A = "I AM VIEW B";
            TempData["C"] = "I AM VIEW C";
            return View();
        }
    }
}

MvcMovie/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MvcMovie/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MvcMovie/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MvcMovie/Views/Home/TourView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TourView</title>
</head>
<body>
    <div> 

        <h1>this is test view</h1>
    </div>
</body>
</html>

MvcMovie/Views/NoteList/Detail.cshtml
@{
    Layout = null;
}
<!DOCTYPE HTML>

<html>
<head>
    <title>English Note</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="@Url.Content("~/Content/main.css")" rel="stylesheet" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

</head>
<body class="landing">
    <!-- body --!>

        <!-- Page Wrapper -->
    <div id="page-wrapper">

        <!-- Header -->
        <header id="header" class="alt">
            <!--<h1><a href="index.html">English</a></h1>-->
            <button onclick="save()" type="button"> save </button>
            <button onclick="prebtn()" type="button"> pre </button>
            <button onclick="nextbtn()" type="button"> next </button>
            <nav id="nav">
                <ul>
                    <li class="special">
                        <a href="#menu" class="menuToggle"><span>Menu</span></a>
                        <div id="menu">
                            <ul>
                                <li><a href="@Url.Action("Index", "NoteList")">Home</a></li>
                                <li><a href="@Url.Action("Word", "NoteList")">Words</a></li>
                                <li><a href="@Url.Action("Sentences", "NoteList")">Sentences</a></li>
                                <li><a href="@Url.Action("Phases", "NoteList")">Phases</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
        </header>


        <section id="banner">
            <div class="inner">
            </div>

        </section>

        <section id="three" class="wrapper style3 special">
            <div class="inner">

                <header class="major"></header>
                <ul class="features"></ul>
            </div>
        </section>


    </div>

    <div id="backCoverMsg"><p>save to homepage</p></div>

    <script src="@Url.Content("~/assets/js/jquery.scrollex.min.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.scrolly.min.js")"></script>
    <script src="@Url.Content("~/assets/js/skel.min.js")"></script>
    <script src="@Url.Content("~/assets/js/util.js")"></script>
    <script src="@Url.Content("~/assets/js/main.js")"></script>
    <script src="@Url.Content("~/assets/js/DataList.js")"></script>


</body>

<script type="text/javascript">


//儲存目前的位置
function save(){

	var _type = $('#wType').val();

	if(_type == 'W'){
		localStorage.lastWord = $('#banner .inner h2').text();
		localStorage.lastWordType = $('#wType').val();
		var d = new Date().getDate();
		var m = new Date().getMonth() + 1; //Month from 0 to 11
		var y = new Date().getFullYear();
		localStorage.indexWordW = nIndex;
		localStorage.lastTimeWord = '' + y + '-' + (m<=9 ? '0' + m : m) + '-' + (d <= 9 ? '0' + d : d);

	}
	else if (_type == 'S'){
	 	localStorage.lastSentence = $('#banner .inner h2').text();
		localStorage.lastSentenceType = 'S';
		var d = new Date().getDate();
		var m = new Date().getMonth() + 1; //Month from 0 to 11
		var y = new Date().getFullYear();
		localStorage.indexWordS = nIndex;
		localStorage.lastTimeSentence = '' + y + '-' + (m<=9 ? '0' + m : m) + '-' + (d <= 9 ? '0' + d : d);
	}
	else{
		localStorage.lastphase = $('#banner .inner h2').text();
		localStorage.lastphaseType = $('#wType').val();
		var d = new Date().getDate();
		var m = new Date().getMonth() + 1;
		var y = new Date().getFullYear();
		localStorage.indexWordP = nIndex;
		localStorage.lastTimePhase = '' + y + '-' + (m<=9 ? '0' + m : m) + '-' + (d <= 9 ? '0' + d : d);
	}

	$("#backCoverMsg").stop(true, true).fadeIn();
	$("#backCoverMsg").stop(true, true).fadeOut(3000);

}


	var parameters = location.search.substring(1).split("&");

    var temp = parameters[0].split("=");
    l = unescape(temp[1]);

	var tempindex = parameters[1].split("=");
    nowIndex = unescape(tempindex[1]);

    var val = DataList[nowIndex];

	var nIndex = parseInt(nowIndex);
   	var val = DataList[nIndex];
 	var Detailtype = val.WordType;

 	var str = '<a id="nclick" href="Detail.html?name=' + val.Word + '&pindex='+nIndex+'"></a>'
 	$('#three .inner').html(str);

//下一個
function nextbtn(){
	var flag = true;
	while(flag){
		nIndex = parseInt(nIndex) + parseInt(1);
		val = DataList[nIndex];
		if (val ==undefined) { return;}
		if(val.WordType != '' || val.WordType != 'undefined'){
			if(Detailtype == val.WordType){
				flag =false;
			}
		}
	}


	output = '<ul class="features">';
	outputbanner = ''
	  if(val.Remark != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<p>' + val.Remark + '</p>';
		output += '</li>';
	  }
	if(val.Sentence != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<p>' + val.Sentence + '</p>';
		output += '</li>';
	}
	if(val.image != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<img src='+val.image+' alt="" />';
		output += '</li>';
	}

	outputbanner +='<h2>'+ val.Word +'</h2>';
	if(val.KK !=='')
		outputbanner +='<div id= "kkname">'+ val.KK +'</p></div>';
	if(val.Explain !== '')
		outputbanner +='<p>'+ val.Explain +'</p>';
	if(val.CreateDate !== '')
		outputbanner +='<p>'+ val.CreateDate +'</p>';
	if(val.pastpp !== '')
		outputbanner +='<p>'+ val.pastpp +'</p>';
	if(val.VoiceLink !=='')
		outputbanner +='<a href = '+val.VoiceLink+'>VoiceLink</a>';

	if(val.WordType !=='')
 		outputbanner +='<input type="hidden" id = "wType" value= '+val.WordType+'>';

	isfind = true;

	output += '</ul>';
	//加入inner
	//加入明細
	$('#three .inner').html(output);
	$('#banner .inner').html(outputbanner);

}

//上一個
function prebtn(){

	var flag = true;
	while(flag){
		nIndex = parseInt(nIndex) - parseInt(1);
		val = DataList[nIndex];
		if (val ==undefined) { return;}
		if(val.WordType != '' || val.WordType != 'undefined'){
			if(Detailtype == val.WordType){
				flag =false;
			}
		}
	}

	output = '<ul class="features">';
	outputbanner = ''
	if(val.Remark != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<p>' + val.Remark + '</p>';
		output += '</li>';
	}
	if(val.Sentence != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<p>' + val.Sentence + '</p>';
		output += '</li>';
	}
	if(val.image != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<img src='+val.image+' alt="" />';
		output += '</li>';
	}

	outputbanner +='<h2>'+ val.Word +'</h2>';
	//kk 音標
	if(val.KK !=='')
		outputbanner +='<div id= "kkname">'+ val.KK +'</p></div>';
	//註解
	if(val.Explain !== '')
		outputbanner +='<p>'+ val.Explain +'</p>';
	//日期
	if(val.CreateDate !== '')
		outputbanner +='<p>'+ val.CreateDate +'</p>';
	//過去是
	if(val.pastpp !== '')
		outputbanner +='<p>'+ val.pastpp +'</p>';
	//字典連結
	if(val.VoiceLink !=='')
		outputbanner +='<a href = '+val.VoiceLink+'>VoiceLink</a>';


	//type : word/sentence/phase
	//
	if(val.WordType !=='')
		outputbanner +='<input type="hidden" id = "wType" value= '+val.WordType+'>';
	isfind = true;
	output += '</ul>';
	$('#three .inner').html(output); //remark
	$('#three .inner').html(output);
	$('#banner .inner').html(outputbanner);

}


	var regex = new RegExp(l, "i");
	var output = '<ul class="features">';
	var outputbanner = ''
	var count = 1;
	var isfind = false;

	if(val.Remark != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<p>' + val.Remark + '</p>';
		output += '</li>';
	}
	if(val.Sentence != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<p>' + val.Sentence + '</p>';
		output += '</li>';
	}
	if(val.image != ''){
		output += ' <li class="icon fa-flag-o">' ;
		output += '<img src='+val.image+' alt="" />';
		output += '</li>';
	}
	//word
	//
	outputbanner +='<h2>'+ val.Word +'</h2>';
	if(val.KK !=='')
		outputbanner +='<div id= "kkname">'+ val.KK +'</p></div>';
	//解釋
	if(val.Explain !== '')
		outputbanner +='<p>'+ val.Explain +'</p>';
	//日期
	if(val.CreateDate !== '')
		outputbanner +='<p>'+ val.CreateDate +'</p>';
	//過去是
	if(val.pastpp !== '')
		outputbanner +='<p>'+ val.pastpp +'</p>';
	//字典蓮姐
	if(val.VoiceLink !=='')
		outputbanner +='<a href = '+val.VoiceLink+'>VoiceLink</a>';

	//word/sentence /phase
	if(val.WordType !=='')
		outputbanner +='<input type="hidden" id = "wType" value= '+val.WordType+'>';

	isfind = true;

	output += '</ul>';
	$('#three .inner').html(output);
	$('#banner .inner').html(outputbanner);


</script>


<script type="text/babel">

</script>
</html>

MvcMovie/Views/NoteList/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE HTML>

<html>
<head>
    <title>English Note</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="@Url.Content("~/assets/css/font-awesome.min.css")"></script>

    <script src="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,800,800italic"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link href="@Url.Content("~/Content/main.css")" rel="stylesheet" type="text/css" />



</head>
<body class="landing">

    <!-- Page Wrapper -->
    <div id="page-wrapper">

        <!-- Header -->
        <header id="header" class="alt">
            <!-- <h1 onclick="save()"><a href="index.html">English</a></h1>-->
            <!--<div onclick="save()"> <h1 >English</h1></div>-->
            <!--<button onclick="save()" type="button"> save </button>-->
            <h1><a href="index.html">English</a></h1>
            <nav id="nav">
                <ul>
                    <li class="special">
                        <a href="#menu" class="menuToggle"><span>Menu</span></a>
                        <div id="menu">
                            <ul>
                                <li><a href="@Url.Action("Index", "NoteList")">Home</a></li>
                                <li><a href="@Url.Action("Word", "NoteList")">Words</a></li>
                                <li><a href="@Url.Action("Sentences", "NoteList")">Sentences</a></li>
                                <li><a href="@Url.Action("Phases", "NoteList")">Phases</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
        </header>


        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <h2>Search</h2>
                <h3>
                    <a href="Word.html?#upstairs">condominium</a>
                </h3>

            </div>
            <div id='output'>


            </div>

            <div class="form-group">
                <h3>search : </h3><input type="input" class="form-control input-lg" id="txt-search" placeholder="Type your search character">
            </div>
            <div id="filter-records"></div>

        </section>

        <section id="one" class="wrapper style1 special">
            <div class="inner">

            </div>
        </section>


    </div>


    <script src="@Url.Content("~/assets/js/jquery.scrollex.min.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.scrolly.min.js")"></script>
    <script src="@Url.Content("~/assets/js/skel.min.js")"></script>
    <script src="@Url.Content("~/assets/js/util.js")"></script>
    <script src="@Url.Content("~/assets/js/main.js")"></script>
    <script src="@Url.Content("~/assets/js/DataList.js")"></script>


</body>

<script type="text/javascript">





$(document).ready(function(){
var outputbanner = ''
	if (typeof(Storage) !== "undefined") {
	    // Store
	    //localStorage.setItem("lastWord", "Smith");
	    // Retrieve
	  var _lastWord =   localStorage.getItem("lastWord");
	   var _lastWordType=  localStorage.getItem("lastWordType");
	   var _lastTime =  localStorage.getItem("lastTimeWord");
	    var _lastIndexW =  localStorage.getItem("indexWordW");
 		outputbanner = '';
 		if (_lastWord === '' && _lastWordType ==='' && _lastTime===''){
 			outputbanner += '<h3>No Record</h3>';
 		}else{
 			if(_lastWord !== ''){
 				outputbanner += '==============================='
 				switch(_lastWordType){

					 case 'W':
	 					outputbanner += '<p>Last reading word: ' ;
					 // outputbanner += '<a name ='+ _lastWord +'></a>'
                        outputbanner += '<a href="Detail?name=' + _lastWord  + '&pindex='+_lastIndexW+ '">'+ _lastWord +'</a>';
					   outputbanner += '</p>';

					   	//outputbanner += '<h3>'+ _lastWord +'</h3>';
	 					 outputbanner += '<p>go to List:' ;
					  //outputbanner += '<a name ='+ _lastWord +'></a>'
					  outputbanner += '<a href="word?#' + _lastIndexW+'">'+ _lastWord + '</a>'
					   outputbanner += '</p>';
					   break;


 				}


 			}

 			if(_lastTime !=='' && _lastTime!=null){
 				 outputbanner += '<p>reading time: ' ;
				  //outputbanner += '<a name ='+ _lastWord +'></a>'
				  outputbanner +=  _lastTime ;
				   outputbanner += '</p>';
 			}

 		}



		var _lastPhase =   localStorage.getItem("lastphase");
	   var _lastPhaseType=  localStorage.getItem("lastphaseType");
	   var _lastTimePhase =  localStorage.getItem("lastTimePhase");
	    var _lastIndexP =  localStorage.getItem("indexWordP");

 		if (_lastPhase == '' && _lastPhaseType =='' && _lastTimePhase==''){
 			outputbanner += '<h3>No Record</h3>';
 		}else{
 			if(_lastWord !== ''){
 				outputbanner += '==============================='
 				switch(_lastPhaseType){

					  case 'P' :
							outputbanner += '<p>Last reading phase: ' ;
						 // outputbanner += '<a name ='+ _lastWord +'></a>'
						  outputbanner += '<a href="Detail?name=' + _lastPhase + '&pindex='+_lastIndexP+ '">'+ _lastPhase +'</a>';
						   outputbanner += '</p>';

		 				    outputbanner += '<p>go to List:' ;
						 
						  outputbanner += '<a href="phase?#' + _lastIndexP+'">'+ _lastPhase + '</a>'
						   outputbanner += '</p>';
						   break;

 				}


 			}

 			if(_lastTimePhase !=='' && _lastTimePhase != null){
 				 outputbanner += '<p>reading time: ' ;
				  //outputbanner += '<a name ='+ _lastWord +'></a>'
				  outputbanner +=  _lastTimePhase ;
				   outputbanner += '</p>';
 			}

 		}



		var _lastSentence =   localStorage.getItem("lastSentence");
	   var _lastSentenceType=  localStorage.getItem("lastSentenceType");
	   var _lastTimeSentence =  localStorage.getItem("lastTimeSentence");
	    var _lastIndexS =  localStorage.getItem("indexWordS");
 		//outputbanner = '';
 		if (_lastSentence === '' && _lastSentenceType ==='' && _lastTimeSentence===''){
 			outputbanner += '<h3>No Record</h3>';
 		}else{
 			if(_lastSentenceType !== ''){
				outputbanner += '==============================='
 				switch(_lastSentenceType){
 					case 'S':
	 					outputbanner += '<p>Last reading sentence: ' ;

					  outputbanner += '<a href="Detail?name=' + _lastSentence + '&pindex='+_lastIndexS+ '">'+ _lastSentence +'</a>';
					   outputbanner += '</p>';

	 					 outputbanner += '<p>go to List:' ;
					  outputbanner += '<a href="Sentence?#' + _lastIndexS+'">'+ _lastSentence + '</a>'
					   outputbanner += '</p>';
					   break;

 				}

 			}

 			if(_lastTimeSentence !=='' && _lastTimeSentence != null){
 				 outputbanner += '<p>reading time: ' ;
				  //outputbanner += '<a name ='+ _lastWord +'></a>'
				  outputbanner +=  _lastTimeSentence ;
				   outputbanner += '</p>';
 			}

 		}


	} else {
	    document.getElementById("result").innerHTML = "Sorry, your browser does not support Web Storage...";
	}
	$('#banner .inner').html(outputbanner);

});

$('#txt-search').keyup(function(){
            var searchField = $(this).val();
			if(searchField === '')  {
				$('#filter-records').html('');
				return;
			}

            var regex = new RegExp(searchField, "i");
            var output = '<header class="major">';
            var count = 1;
			  $.each(DataList, function(key, val){
			  	var nkey = Object.keys(DataList)[key];
				if ((val.Word.search(regex) != -1)) {
					
	  					output += '<h3>' ;
					  output += '<a href="Detail?name=' + val.Word + '&pindex='+nkey+ '"</a>'+ val.Word
					   output += '</h3></br>';

				}else if ((val.Remark.search(regex) != -1)){
					
					output += '<h3>' ;
				  	output += '<a href="Detail?name=' + val.Word + '&pindex='+nkey+ '"</a>'+ val.Word
				   	output += '</h3></br>';
				   
				}
			  });
			  output += '</header>';
			  $('#one .inner').html(output);
        });
</script>


<script type="text/babel">

</script>
</html>

MvcMovie/Views/NoteList/Phases.cshtml
@{
    Layout = null;
}
<!DOCTYPE HTML>
<!--
    Spectral by HTML5 UP
    html5up.net |
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>English Note</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="@Url.Content("~/Content/main.css")" rel="stylesheet" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

</head>
<body class="landing">

    <!-- Page Wrapper -->
    <div id="page-wrapper">

        <!-- Header -->
        <header id="header" class="alt">
            <h1><a href="index.html">English222</a></h1>
            <nav id="nav">
                <ul>
                    <li class="special">
                        <a href="#menu" class="menuToggle"><span>Menu</span></a>
                        <div id="menu">
                            <ul>
                                <li><a href="@Url.Action("Index", "NoteList")">Home</a></li>
                                <li><a href="@Url.Action("Word", "NoteList")">Words</a></li>
                                <li><a href="@Url.Action("Sentences", "NoteList")">Sentences</a></li>
                                <li><a href="@Url.Action("Phases", "NoteList")">Phases</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
        </header>


        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <h2>Phases</h2>

            </div>

        </section>

        <!-- One -->
        <section id="one" class="wrapper style1 special">
            <div class="inner">
                <header class="major"></header>

            </div>
        </section>
        <div id="container">
        </div>
    </div>
    <script src="@Url.Content("~/assets/js/jquery.scrollex.min.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.scrolly.min.js")"></script>
    <script src="@Url.Content("~/assets/js/skel.min.js")"></script>
    <script src="@Url.Content("~/assets/js/util.js")"></script>
    <script src="@Url.Content("~/assets/js/main.js")"></script>
    <script src="@Url.Content("~/assets/js/DataList.js")"></script>

</body>

<script type="text/javascript">


$(document).ready(function(){

	var output = '<header class="major">';
	var outputbanner = ''
	var count = 1;
	$.each(DataList, function(key, val){
	if ((val.WordType == 'P')) {
		var nkey = Object.keys(DataList)[key];
		output += '<p>' ;
		output += '<a name ='+ nkey +'></a>'
		output += '<a href="Detail?name=' + val.Word.replace(/ /g,"-") + '&pindex='+nkey+'"</a>'+ val.Word
		output += '</p></br>';

	}
	});
	output += '</header>';
	$('#one .inner').html(output);




});



</script>


<script type="text/babel">

</script>
</html>

MvcMovie/Views/NoteList/Sentences.cshtml
@{
    Layout = null;
}
<!DOCTYPE HTML>

<html>
<head>
    <title>English Note</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link href="@Url.Content("~/Content/main.css")" rel="stylesheet" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

</head>
<body class="landing">

    <!-- Page Wrapper -->
    <div id="page-wrapper">

        <!-- Header -->
        <header id="header" class="alt">
            <h1><a href="index.html">English</a></h1>
            <nav id="nav">
                <ul>
                    <li class="special">
                        <a href="#menu" class="menuToggle"><span>Menu</span></a>
                        <div id="menu">
                            <ul>
                                <li><a href="@Url.Action("Index", "NoteList")">Home</a></li>
                                <li><a href="@Url.Action("Word", "NoteList")">Words</a></li>
                                <li><a href="@Url.Action("Sentences", "NoteList")">Sentences</a></li>
                                <li><a href="@Url.Action("Phases", "NoteList")">Phases</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
        </header>


        <section id="banner">
            <div class="inner">
                <h2>Sentences</h2>
            </div>

        </section>

        <!-- One -->
        <section id="one" class="wrapper style1 special">
            <div class="inner">
                <header class="major"></header>

            </div>
        </section>

    </div>

    <script src="@Url.Content("~/assets/js/jquery.scrollex.min.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.scrolly.min.js")"></script>
    <script src="@Url.Content("~/assets/js/skel.min.js")"></script>
    <script src="@Url.Content("~/assets/js/util.js")"></script>
    <script src="@Url.Content("~/assets/js/main.js")"></script>
    <script src="@Url.Content("~/assets/js/DataList.js")"></script>


</body>

<script type="text/javascript">


$(document).ready(function(){

	var output = '<header class="major">';
	var outputbanner = ''
	var count = 1;
	$.each(DataList, function(key, val){
		if ((val.WordType == 'S')) {
			var nkey = Object.keys(DataList)[key];
			output += '<p>' ;
			output += '<a name ='+ nkey +'></a>'
			output += '<a href="Detail?name=' + val.Word + '&pindex='+nkey+ '"</a>'+ val.Word
			output += '</p></br>';
		}
	});
	output += '</header>';
	$('#one .inner').html(output);

});



</script>

</html>

MvcMovie/Views/TourMVC/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h1>THIS MVCController</h1>
    </div>
</body>
</html>